# Generated by Django 5.2.4 on 2025-07-10 22:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
            },
        ),
        migrations.CreateModel(
            name='Dupla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogadores', models.ManyToManyField(to='jogos.jogador')),
            ],
            options={
                'verbose_name': 'Dupla',
                'verbose_name_plural': 'Duplas',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('pontos_dupla1', models.PositiveIntegerField()),
                ('pontos_dupla2', models.PositiveIntegerField()),
                ('dupla1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_dupla1', to='jogos.dupla')),
                ('dupla2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_dupla2', to='jogos.dupla')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['-data'],
            },
        ),
    ]
